export enum ROUTES {
  HOME = "",
  LOGIN = "login",
  AUTH_CALLBACK = "auth/callback",
  COURSES = "courses",
  SUPERADMIN = "superadmin",
  ADMIN = "admin",
  COMPANY = "company",
  COMPANY_BY_ID = "company/:id",
  COURSE_BY_ID = "course/:id",
  COURSE = "course",
  REVIEW = "review",
  UNAUTHORIZED = "unauthorized",
  PROFILE = "me",
}